<a href="https://colab.research.google.com/github/harshit00052/RealWorldDataPractice/blob/main/Copy_of_session_19_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [180]:
import pandas as pd

## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [181]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

In [182]:
titanic_df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
494,495,0,3,"Stanley, Mr. Edward Roland",male,21.0,0,0,A/4 45380,8.0500,NaN,S
747,748,1,2,"Sinkkonen, Miss. Anna",female,30.0,0,0,250648,13.0000,NaN,S
203,204,0,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,NaN,C

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [183]:
temp_gdf = titanic_df.groupby(titanic_df['Pclass'])

In [184]:
temp_gdf.agg({'Age':'mean'})

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

In [185]:
for group , df in temp_gdf:
  print('group', group , df[df['Age'].isnull()].size)

group 1 360
group 2 132
group 3 1632

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [186]:
for group , df in temp_gdf:
  mod = df['Embarked'].mode()
  print(group, mod[0])

1 S
2 S
3 S

In [187]:
titanic_df['Embarked'] = titanic_df.groupby(titanic_df['Pclass'])['Embarked'].transform(lambda x: x.fillna(x.mode().iloc[0]))

In [188]:
for group , df in temp_gdf:
  print("group ",group)
  print(df['Embarked'].value_counts(ascending=True),'\n')

group  1
Embarked
Q      2
C     85
S    129
Name: count, dtype: int64

group  2
Embarked
Q      3
C     17
S    164
Name: count, dtype: int64

group  3
Embarked
C     66
Q     72
S    353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [189]:
emg = titanic_df.groupby(titanic_df['Embarked'])
for group , df in emg:
  print("group ",group)
  print(df.groupby(df['Pclass']).agg({'Fare':'mean'}).round(2), '\n')

group  C
          Fare
Pclass
1       104.72
2        25.36
3        11.21

group  Q
         Fare
Pclass
1       90.00
2       12.35
3       11.18

group  S
         Fare
Pclass
1       70.51
2       20.33
3       14.64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [190]:
fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [191]:
fifa_df.sample(5)
fifa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

In [192]:
fifa_df['Passes'].min()

225

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [193]:
def z_normalization(group, cols_to_perform):
  tcol = group[cols_to_perform]
  return (tcol-tcol.mean())/tcol.std();

In [194]:
norm_df = fifa_df.groupby('Team').apply(z_normalization, cols_to_perform = ['Passes', 'Passes Completed', 'Attempted Line Breaks', 'Completed Line Breaks'])

/tmp/ipykernel_881/95993954.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  norm_df = fifa_df.groupby('Team').apply(z_normalization, cols_to_perform = ['Passes', 'Passes Completed', 'Attempted Line Breaks', 'Completed Line Breaks'])

In [195]:
norm_df

                 Passes  Passes Completed  Attempted Line Breaks  \
Team
Argentina 8   -0.208138         -0.157888               0.364745
          46  -0.630447         -0.574048              -0.795806
          77   1.685214          1.813757              -1.027917
          98   0.622403          0.592566               0.003684
          115 -0.137753         -0.253400               0.571065
...                 ...               ...                    ...
Uruguay   63  -0.931702         -0.894617              -0.484182
          89  -0.124867         -0.184945               1.149932
Wales     7   -0.054584         -0.139325               0.226294
          32   1.026174          1.062357               0.867461
          68  -0.971590         -0.923031              -1.093756

               Completed Line Breaks
Team
Argentina 8                 0.087403
          46               -0.945040
          77                0.049164
          98                0.393311
          115              -0.103791
...                              ...
Uruguay   63               -0.623480
          89                1.153437
Wales     7                 0.195342
          32                0.887916
          68               -1.083258

[128 rows x 4 columns]

In [196]:
temp_group = fifa_df.groupby('Team')
for group, tdf in temp_group:
  print("Team",group)
  print("minimum Passess ",tdf['Passes'].min())
  print("maximum Passess ",tdf['Passes'].max())
  print("average Yellow Cards",tdf['Yellow Cards'].mean().round(2))
  print('\n')

Team Argentina
minimum Passess  408
maximum Passess  862
average Yellow Cards 2.29


Team Australia
minimum Passess  286
maximum Passess  466
average Yellow Cards 1.75


Team Belgium
minimum Passess  512
maximum Passess  685
average Yellow Cards 1.67


Team Brazil
minimum Passess  548
maximum Passess  695
average Yellow Cards 1.2


Team Cameroon
minimum Passess  295
maximum Passess  500
average Yellow Cards 2.67


Team Canada
minimum Passess  448
maximum Passess  536
average Yellow Cards 2.67


Team Costa Rica
minimum Passess  231
maximum Passess  454
average Yellow Cards 2.0


Team Croatia
minimum Passess  461
maximum Passess  724
average Yellow Cards 1.14


Team Denmark
minimum Passess  537
maximum Passess  650
average Yellow Cards 1.67


Team Ecuador
minimum Passess  429
maximum Passess  484
average Yellow Cards 1.0


Team England
minimum Passess  508
maximum Passess  810
average Yellow Cards 0.2


Team France
minimum Passess  358
maximum Passess  734
average Yellow Cards 1.14


Team Germany
minimum Passess  352
maximum Passess  827
average Yellow Cards 1.0


Team Ghana
minimum Passess  319
maximum Passess  460
average Yellow Cards 2.67


Team Iran
minimum Passess  232
maximum Passess  463
average Yellow Cards 2.33


Team Japan
minimum Passess  225
maximum Passess  591
average Yellow Cards 1.5


Team Korea Republic
minimum Passess  359
maximum Passess  548
average Yellow Cards 1.5


Team Mexico
minimum Passess  356
maximum Passess  500
average Yellow Cards 2.33


Team Morocco
minimum Passess  229
maximum Passess  583
average Yellow Cards 1.29


Team Netherlands
minimum Passess  403
maximum Passess  786
average Yellow Cards 1.8


Team Poland
minimum Passess  303
maximum Passess  466
average Yellow Cards 1.75


Team Portugal
minimum Passess  461
maximum Passess  678
average Yellow Cards 1.2


Team Qatar
minimum Passess  424
maximum Passess  457
average Yellow Cards 2.33


Team Saudi Arabia
minimum Passess  267
maximum Passess  560
average Yellow Cards 4.67


Team Senegal
minimum Passess  277
maximum Passess  511
average Yellow Cards 1.75


Team Serbia
minimum Passess  403
maximum Passess  513
average Yellow Cards 4.0


Team Spain
minimum Passess  647
maximum Passess  1070
average Yellow Cards 0.5


Team Switzerland
minimum Passess  403
maximum Passess  512
average Yellow Cards 2.25


Team Tunisia
minimum Passess  328
maximum Passess  501
average Yellow Cards 1.67


Team United States
minimum Passess  427
maximum Passess  572
average Yellow Cards 1.25


Team Uruguay
minimum Passess  390
maximum Passess  528
average Yellow Cards 2.0


Team Wales
minimum Passess  325
maximum Passess  508
average Yellow Cards 1.67

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

In [197]:
ipl_df = pd.read_csv('/content/ipl_deliveries - ipl_deliveries.csv')

In [244]:
ipl_df.sample(1)

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
129675,729293,Chennai Super KingsDelhi Daredevils,2,8,3,LRPL Taylor,DR Smith,KD Karthik,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Daredevils,Chennai Super Kings

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [200]:
ipl_df[ipl_df['innings']==2].groupby('batter').agg({'total_run':'sum'}).reset_index().sort_values('total_run', ascending=False).head(1)

      batter  total_run
524  V Kohli       3163

In [212]:
def find_strike_rate(group, cols):
  g_col = group[cols]
  balls = len(g_col)
  if(balls>100):
    return (g_col.sum()/balls)*100

ipl_df.groupby('batter').apply(find_strike_rate, cols='total_run', include_groups=False).dropna().sort_values(ascending=False)

batter
AD Russell        177.722772
BCJ Cutting       171.917808
K Gowtham         166.956522
SP Narine         165.813253
LS Livingstone    165.625000
                     ...
GH Vihari          91.540785
Z Khan             85.815603
Kuldeep Yadav      85.384615
CJ Ferguson        84.873950
RT Ponting         80.620155
Length: 265, dtype: float64

In [227]:
temp_ipl_df = ipl_df.groupby('batter').agg({'total_run':['sum', 'count']}).reset_index()
temp_ipl_df = temp_ipl_df[temp_ipl_df['total_run']['count']>100]
temp_ipl_df['strike_rate'] = (temp_ipl_df['total_run']['sum']/temp_ipl_df['total_run']['count'])*100
temp_ipl_df.sort_values(by='strike_rate',ascending=False)

             batter total_run       strike_rate
                          sum count
36       AD Russell      2154  1212  177.722772
91      BCJ Cutting       251   146  171.917808
245       K Gowtham       192   115  166.956522
508       SP Narine      1101   664  165.813253
292  LS Livingstone       583   352  165.625000
..              ...       ...   ...         ...
180       GH Vihari       303   331   91.540785
604          Z Khan       121   141   85.815603
279   Kuldeep Yadav       111   130   85.384615
111     CJ Ferguson       101   119   84.873950
449      RT Ponting       104   129   80.620155

[265 rows x 4 columns]

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [275]:
ipl_df.groupby(['batter','bowler']).agg({'isWicketDelivery':'sum', 'total_run':'sum'}).sort_values(['isWicketDelivery', 'total_run'], ascending=[False,True])

                           isWicketDelivery  total_run
batter     bowler
RG Sharma  SP Narine                      8        140
PA Patel   B Kumar                        7         72
MS Dhoni   Z Khan                         7         78
V Kohli    Sandeep Sharma                 7         79
RG Sharma  A Mishra                       7         87
...                                     ...        ...
N Rana     R Ashwin                       0        101
KD Karthik JD Unadkat                     0        106
SA Yadav   R Ashwin                       0        109
SR Watson  Sandeep Sharma                 0        109
KL Rahul   DL Chahar                      0        124

[24213 rows x 2 columns]

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [279]:
ipl_df.groupby(['batter', 'non-striker']).agg({'total_run':'sum'}).sort_values(by='total_run',ascending=False)

                               total_run
batter         non-striker
AB de Villiers V Kohli              1623
CH Gayle       V Kohli              1617
V Kohli        AB de Villiers       1511
DA Warner      S Dhawan             1420
V Kohli        CH Gayle             1185
...                                  ...
P Negi         TG Southee              0
KM Jadhav      AF Milne                0
KK Nair        K Rabada                0
SP Jackson     SW Billings             0
Z Khan         S Aravind               0

[8062 rows x 1 columns]

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [298]:
partner_df = ipl_df.groupby(['batter', 'non-striker']).agg(runs=('total_run','sum'), balls=('total_run','count')).reset_index().sort_values(by='runs', ascending=False)

        batter    non-striker  runs  balls
598  AM Rahane      MK Lomror    21     15
675   AR Patel  Kuldeep Yadav    40     19

In [299]:
partner_df['strike_rate'] = (partner_df['runs']/partner_df['balls'])*100;

In [301]:
partner_df.sample(5)

                batter   non-striker  runs  balls  strike_rate
6328           S Sohal     IK Pathan    17     12   141.666667
5495          R Sharma    AD Mathews     0      1     0.000000
5318          R Bhatia  Ankit Sharma     4      3   133.333333
4654  Mujeeb Ur Rahman    AS Rajpoot    11      5   220.000000
7360        TL Seifert       PP Shaw    26     21   123.809524