<a href="https://colab.research.google.com/github/harshit00052/RealWorldDataPractice/blob/main/IMDB50KREVIEWS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/IMDB Dataset.csv')

In [90]:
df.sample(2)

                                                  review sentiment
38224  pinjar by mr dwivedi is an awesome movie. its ...  positive
11979  hercules wound up falling into the same catego...  negative

In [12]:
df = df.drop_duplicates()

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49582 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     49582 non-null  object
 1   sentiment  49582 non-null  object
dtypes: object(2)
memory usage: 1.1+ MB

#lower case conversion

In [17]:
df.loc[:,'review'] = df['review'].astype(str).str.lower()

#removing spaces

In [26]:
df.loc[:,'review'] = df['review'].astype(str).str.strip()

In [30]:
df['review'].astype(str).str.contains(r'^\s|\s$', na=False).any()

np.False_

#removing tags

In [34]:
df.loc[:,'review'] = df['review'].astype(str).str.replace('<.*?>','', regex=True)

# import re
# def removetags(data):
#   data = re.sub(r'<.*?>', '', data)
#   return data

# df['review'] = removetags(df['review'])

In [35]:
df['review'].astype(str).str.contains(r'<.*?>', na=False).any()

np.False_

#removing url's

In [37]:
df.loc[:,'review'] = df['review'].astype(str).str.replace(r'https?://\S+|www\.\S+','', regex=True)

In [38]:
df['review'].astype(str).str.contains(r'https?://\S+|www\.\S+', na=False).any()

np.False_

#expanding  contractions

#observations (SOLVED)
and shecan't, photographyeditorcan't, sicily who _can't_ make a,  can'tcha tell?", hers, theyhaven't changed, couldn'tsing, couldn'tact ,  i'llkick you

In [40]:
!pip install contractions

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (13 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 9.2 MB/s eta 0:00:00
Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 10.4 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.1 textsearch-0.0.24

In [65]:
import re
def separate_contractions(text):
    if not isinstance(text, str):
        return text
    # Separate common contractions stuck to previous word
    text = re.sub(
        r'([a-zA-Z])('
        r"n't|'ll|'re|'ve|'d|'m|'s"
        r')\b',
        r'\1 \2',
        text
    )

    return text

In [73]:
import re

def separate_after_contractions(text):
    return re.sub(
        r"(n't|'ll|'re|'ve|'d|'m|'s)([A-Za-z])",
        r"\1 \2",
        text
    )

In [74]:
import contractions

df['review'] = df['review'].astype(str).apply(separate_after_contractions).apply(separate_contractions).apply(contractions.fix)

In [76]:
df['review'].astype(str).str.contains("haven't", na=False).any()

np.False_

In [77]:
df['review'].astype(str).str.contains("couldn't", na=False).any()

np.False_

#expanding abbreviations

In [78]:
ABBREVIATIONS = {
    "u": "you",
    "ur": "your",
    "idk": "i do not know",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "btw": "by the way",
    "thx": "thanks",
    "pls": "please",
    "plz": "please",
    "asap": "as soon as possible",
    "bc": "because",
    "bcz": "because",
    "cuz": "because",
    "coz": "because",
    "msg": "message",
    "tmrw": "tomorrow",
    "w/": "with",
    "w/o": "without",
    "omg": "oh my god",
    "lol": "laugh out loud",
    "lmao": "laughing my ass off",
    "rofl": "rolling on the floor laughing",
    "tbh": "to be honest",
    "fyi": "for your information",
    "afaik": "as far as i know"
}

In [79]:
import re

def expand_abbreviations(text):
    if not isinstance(text, str):  # This line returns as soon as the input is non string
        return text

    pattern = r'\b(' + '|'.join(map(re.escape, ABBREVIATIONS.keys())) + r')\b'  # This line builds a regular expression dynamically from your abbreviation dictionary

    return re.sub(
        pattern,
        lambda m: ABBREVIATIONS[m.group().lower()],
        text,
        flags=re.IGNORECASE
    )

In [80]:
df['review'] = df['review'].apply(expand_abbreviations)

#remove punctuation marks

In [91]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [93]:
df.loc[:,'review'] = df['review'].astype(str).str.replace(f"[{re.escape(string.punctuation)}]", "", regex=True)

In [95]:
df['review'].astype(str).str.contains(f"[{re.escape(string.punctuation)}]", na=False).any()

np.False_

#observing agin for last time

i have performed sample code multiple times and concuded the data is cleaned enough and now good for move to next step

In [89]:
df.sample(1)

                                                  review sentiment
19877  firstly, i will not tell you why i rented this...  negative